pub mod cli;
pub mod cloud_client;
#[cfg(feature = "cloud-server")]
pub mod cloud_server;
pub mod cloud_sync;
pub mod compound_lexer;
pub mod config_io;
pub mod core;
#[cfg(unix)]
pub mod daemon;
#[cfg(unix)]
pub mod daemon_client;
pub mod dashboard;
pub mod doctor;
pub mod dropin;
pub mod engine;
pub mod heatmap;
pub mod hook_handlers;
pub mod hooks;
#[cfg(feature = "http-server")]
pub mod http_server;
pub mod instructions;
pub mod marked_block;
pub mod mcp_stdio;
#[cfg(feature = "http-server")]
pub mod proxy;
pub mod proxy_autostart;
pub mod proxy_setup;
pub mod report;
pub mod rewrite_registry;
pub mod rules_inject;
pub mod server;
pub mod setup;
pub mod shell;
pub mod shell_hook;
pub mod status;
pub mod terminal_ui;
pub mod token_report;
pub mod tool_defs;
pub mod tools;
pub mod tui;
pub mod uninstall;
