//! Standalone dependency-direction guard for the public Rust client.

use std::process::Command;
use std::{fs, path::Path};

use serde_json::Value;

const CRATES_IO_SOURCE: &str = "registry+https://github.com/rust-lang/crates.io-index";
const LOCK: &str = include_str!("../Cargo.lock");
const MANIFEST: &str = include_str!("../Cargo.toml");

#[test]
fn release_identity_and_msrv_are_locked() {
    assert!(MANIFEST.contains("version = \"0.2.0\""));
    assert!(MANIFEST.contains("rust-version = \"1.74\""));
    for exact in [
        "\"=2.9.7\"",
        "\"=2.4.1\"",
        "\"=1.7.0\"",
        "\"=1.5.0\"",
        "\"=1.0.193\"",
        "\"=1.0.108\"",
        "\"=1.0.50\"",
        "\"=0.2.186\"",
        "\"=0.8.11\"",
        "\"=0.17.1\"",
        "\"=0.3.36\"",
        "\"=1.6.1\"",
    ] {
        assert!(MANIFEST.contains(exact), "MSRV-critical pin drift: {exact}");
    }
    assert!(LOCK.starts_with(
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 3\n"
    ));
    assert!(LOCK.contains("name = \"lean-ctx-client\"\nversion = \"0.2.0\""));
}

#[test]
fn cargo_metadata_has_no_engine_private_or_path_dependencies() {
    let output = Command::new(env!("CARGO"))
        .args(["metadata", "--locked", "--format-version", "1"])
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output()
        .expect("cargo metadata starts");
    assert!(
        output.status.success(),
        "cargo metadata failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let metadata: Value = serde_json::from_slice(&output.stdout).expect("metadata JSON");
    let packages = metadata["packages"].as_array().expect("packages array");
    for package in packages {
        let name = package["name"].as_str().expect("package name");
        if name == env!("CARGO_PKG_NAME") {
            for dependency in package["dependencies"]
                .as_array()
                .expect("dependency array")
            {
                assert!(
                    dependency["path"].is_null(),
                    "path dependency is forbidden: {}",
                    dependency["name"]
                );
                assert_eq!(
                    dependency["source"].as_str(),
                    Some(CRATES_IO_SOURCE),
                    "direct dependency must resolve from public crates.io: {}",
                    dependency["name"]
                );
            }
            continue;
        }

        assert!(
            !name.starts_with("lean-ctx") && !name.starts_with("lean_ctx"),
            "engine/private package dependency is forbidden: {name}"
        );
        assert_eq!(
            package["source"].as_str(),
            Some(CRATES_IO_SOURCE),
            "transitive dependency must resolve from public crates.io: {name}"
        );
    }
}

#[test]
fn committed_lock_has_only_public_registry_sources() {
    let mut package_name = None;
    let mut package_source = None;

    let check_package = |name: Option<&str>, source: Option<&str>| {
        let Some(name) = name else {
            return;
        };
        if name == env!("CARGO_PKG_NAME") {
            assert!(source.is_none(), "root package must remain source-less");
        } else {
            assert!(
                !name.starts_with("lean-ctx") && !name.starts_with("lean_ctx"),
                "engine/private package is forbidden in Cargo.lock: {name}"
            );
            assert_eq!(
                source,
                Some(CRATES_IO_SOURCE),
                "non-public lock source for {name}"
            );
        }
    };

    for line in LOCK.lines().chain(std::iter::once("[[package]]")) {
        if line == "[[package]]" {
            check_package(package_name.as_deref(), package_source.as_deref());
            package_name = None;
            package_source = None;
        } else if let Some(value) = line.strip_prefix("name = ") {
            package_name = parse_quoted(value).map(ToOwned::to_owned);
        } else if let Some(value) = line.strip_prefix("source = ") {
            package_source = parse_quoted(value).map(ToOwned::to_owned);
        }
    }

    assert!(
        !LOCK.contains("path+") && !LOCK.contains("git+"),
        "Cargo.lock contains a path or git source"
    );
}

#[test]
fn monorepo_publish_workflow_uses_manifest_version_and_idempotent_registry_probe() {
    let workflow = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../..")
        .join(".github/workflows/publish-clients.yml");
    if !workflow.exists() {
        return;
    }
    let workflow = fs::read_to_string(workflow).expect("read publish workflow");
    assert!(workflow.contains("CRATE_VERSION=\"$(grep -m1 '^version' Cargo.toml | sed -E"));
    assert!(workflow.contains("crates.io/api/v1/crates/lean-ctx-client/${CRATE_VERSION}"));
    assert!(workflow.contains("cargo publish --token \"${CARGO_REGISTRY_TOKEN}\""));
}

fn parse_quoted(value: &str) -> Option<&str> {
    value.strip_prefix('"')?.strip_suffix('"')
}
