#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate or verify deterministic Rust third-party notices and CycloneDX."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "rust/Cargo.toml"
NOTICE = ROOT / "THIRD_PARTY_NOTICES"
SBOM = ROOT / "SBOM.cdx.json"


def metadata() -> dict[str, Any]:
    output = subprocess.check_output(
        ["cargo", "metadata", "--locked", "--format-version", "1",
         "--manifest-path", str(MANIFEST)],
        cwd=ROOT,
    )
    return json.loads(output)


def packages(metadata: dict[str, Any]) -> list[dict[str, Any]]:
    values: dict[tuple[str, str, str], dict[str, Any]] = {}
    for package in metadata["packages"]:
        source = package.get("source")
        if source is None:
            continue
        key = (package["name"], package["version"], source)
        values[key] = package
    return [values[key] for key in sorted(values)]


def notice_text(items: list[dict[str, Any]]) -> str:
    lines = [
        "# Third-party notices",
        "",
        "Generated by `scripts/check-third-party-artifacts.py` from the locked Rust",
        "dependency graph. License expressions are dependency metadata, not legal advice.",
        "The corresponding license texts remain available from each source package.",
        "",
        "| Package | Version | License expression | Source |",
        "| --- | --- | --- | --- |",
    ]
    for item in items:
        license_value = item.get("license") or "NOASSERTION"
        source = item["source"].replace("|", "%7C")
        lines.append(
            f"| {item['name']} | {item['version']} | {license_value} | `{source}` |"
        )
    lines.extend(["", "Review cargo-deny output for compatibility and advisory policy.", ""])
    return "\n".join(lines)


def project_version(metadata: dict[str, Any]) -> str:
    manifest = MANIFEST.resolve()
    for package in metadata["packages"]:
        if Path(package["manifest_path"]).resolve() == manifest:
            return str(package["version"])
    raise ValueError("lean-ctx root package missing from cargo metadata")


def sbom_text(items: list[dict[str, Any]], version: str) -> str:
    components = []
    for item in items:
        name, version = item["name"], item["version"]
        component: dict[str, Any] = {
            "type": "library",
            "bom-ref": f"pkg:cargo/{name}@{version}",
            "name": name,
            "version": version,
            "purl": f"pkg:cargo/{name}@{version}",
            "licenses": [{"expression": item.get("license") or "NOASSERTION"}],
        }
        repository = item.get("repository")
        if repository:
            component["externalReferences"] = [
                {"type": "vcs", "url": repository}
            ]
        components.append(component)
    document = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "name": "lean-ctx",
                "version": version,
            }
        },
        "components": components,
    }
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def update_or_check(path: Path, expected: str, check: bool) -> bool:
    if check:
        try:
            current = path.read_text(encoding="utf-8")
        except OSError:
            print(f"ERROR: missing generated artifact {path.name}", file=sys.stderr)
            return False
        if current != expected:
            print(f"ERROR: stale generated artifact {path.name}", file=sys.stderr)
            return False
        return True
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        cargo_metadata = metadata()
        items = packages(cargo_metadata)
        version = project_version(cargo_metadata)
    except (OSError, ValueError, json.JSONDecodeError, subprocess.CalledProcessError) as error:
        print(f"dependency inventory: {error}", file=sys.stderr)
        return 1
    missing = sorted(
        f"{item['name']}@{item['version']}" for item in items if not item.get("license")
    )
    if missing:
        for item in missing:
            print(f"ERROR: dependency lacks license metadata: {item}", file=sys.stderr)
        return 1
    ok = update_or_check(NOTICE, notice_text(items), args.check)
    ok = update_or_check(SBOM, sbom_text(items, version), args.check) and ok
    if not ok:
        return 1
    print(f"third-party artifacts OK: {len(items)} locked packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
