mod agent_cmd;
mod allow_cmd;
pub mod audit_report;
mod call_cmd;
mod cheatsheet_cmd;
pub mod cloud;
mod common;
mod compliance_cmd;
mod compress_cmd;
mod config_cmd;
mod context_cmd;
mod debug_log_cmd;
mod discover_cmd;
pub mod dispatch;
pub mod eval_cmd;
pub mod export_rules;
pub mod harden;
mod index_cmd;
mod init_cmd;
mod instructions_cmd;
mod introspect_cmd;
mod knowledge_cmd;
mod learn_cmd;
mod ledger_cmd;
mod overview_cmd;
mod pack_cmd;
pub mod plugin_cmd;
mod policy_cmd;
mod policy_enforce_cmd;
mod policy_org_cmd;
mod profile_cmd;
pub(crate) mod prompt;
mod proof_cmd;
mod read_cmd;
mod repomap_cmd;
mod roi_cmd;
pub mod rules_cmd;
pub mod rules_dedup;
mod security_cmd;
mod semantic_search_cmd;
mod session_cmd;
mod shell_init;
mod skillify_cmd;
mod summary_cmd;
mod tee_cmd;
mod theme_cmd;
mod tools_health_cmd;
mod trust_cmd;
mod upgrade_hint;
mod verify_cache_cmd;
mod verify_cmd;
mod visualize_cmd;
pub(crate) mod wrapped_publish;

pub(crate) use agent_cmd::cmd_agent;
pub use allow_cmd::cmd_allow;
pub(crate) use call_cmd::cmd_call;
pub use cheatsheet_cmd::*;
pub use common::load_shell_history_pub;
pub(crate) use compliance_cmd::cmd_compliance;
pub(crate) use compress_cmd::cmd_compress;
pub use config_cmd::*;
pub(crate) use context_cmd::{cmd_compile, cmd_control, cmd_plan};
pub(crate) use debug_log_cmd::cmd_debug_log;
pub use discover_cmd::*;
pub use dispatch::run;
pub(crate) use index_cmd::cmd_index;
pub(crate) use init_cmd::quiet_enabled;
pub use init_cmd::{cmd_init, cmd_init_quiet};
pub(crate) use instructions_cmd::cmd_instructions;
pub(crate) use introspect_cmd::cmd_introspect;
pub(crate) use knowledge_cmd::cmd_knowledge;
pub(crate) use learn_cmd::cmd_learn;
pub use ledger_cmd::*;
pub(crate) use overview_cmd::cmd_overview;
pub(crate) use pack_cmd::cmd_pack;
pub(crate) use policy_cmd::cmd_policy;
pub use profile_cmd::*;
pub(crate) use proof_cmd::cmd_proof;
pub use read_cmd::*;
pub(crate) use repomap_cmd::cmd_repomap;
pub(crate) use roi_cmd::cmd_roi;
pub(crate) use security_cmd::{cmd_secure, cmd_security, cmd_yolo};
pub(crate) use semantic_search_cmd::cmd_semantic_search;
pub use session_cmd::*;
pub use shell_init::*;
pub(crate) use skillify_cmd::cmd_skillify;
pub(crate) use summary_cmd::cmd_summary;
pub use tee_cmd::*;
pub use theme_cmd::*;
pub(crate) use tools_health_cmd::cmd_tools_health;
pub(crate) use trust_cmd::{cmd_trust, cmd_untrust};
pub(crate) use verify_cmd::cmd_verify;
pub(crate) use visualize_cmd::cmd_visualize;
