// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  site: 'https://leanctx.com',
  trailingSlash: 'always',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  redirects: {
    '/benchmark/': '/context-os/benchmark/',
    // Commercial / internal pages → homepage
    '/checkout/': '/',
    '/pro/': '/',
    '/login/': '/',
    '/dashboard/': '/',
    '/cloud/': '/',

    // Redundant product pages
    '/features/': '/how-it-works/',
    '/cli/': '/docs/cli-reference/',
    '/shell-hook/': '/docs/cli-reference/',
    '/manifest/': '/docs/tools/',
    '/mcp-server/': '/docs/tools/',
    '/context-governance/': '/context-os/',
    '/safety/': '/docs/security/',
    '/limitations/': '/docs/security/',

    // Context OS subpages → main context-os page
    '/context-os/smart-io/': '/context-os/',
    '/context-os/intelligence/': '/context-os/',
    '/context-os/memory/': '/context-os/',
    '/context-os/governance/': '/context-os/',
    '/context-os/verification/': '/context-os/',
    '/context-os/integrations/': '/context-os/',
    '/context-os/context-bus/': '/context-os/',
    '/context-os/shared-sessions/': '/context-os/',
    '/context-os/sdk/': '/context-os/',

    // Deleted docs → appropriate targets
    '/docs/agent-harness/': '/docs/getting-started/',
    '/docs/analytics/': '/docs/getting-started/',
    '/docs/ccp/': '/docs/concepts/protocols/',
    '/docs/cep/': '/docs/concepts/protocols/',
    '/docs/tdd/': '/docs/getting-started/',
    '/docs/cloud/': '/docs/getting-started/',
    '/docs/http-mcp/': '/docs/api-reference/',
    '/docs/context-field-theory/': '/docs/concepts/read-modes/',
    '/docs/context-packages/': '/docs/tools/',
    '/docs/contracts/': '/docs/concepts/protocols/',
    '/docs/graph/': '/docs/tools/',
    '/docs/ide-setup/': '/docs/getting-started/',
    '/docs/intelligence-layer/': '/docs/concepts/read-modes/',
    '/docs/observability/': '/docs/getting-started/',
    '/docs/profiles/': '/docs/configuration/',
    '/docs/remote-setup/': '/docs/getting-started/',
    '/docs/replayability/': '/docs/getting-started/',
    '/docs/token-guide/': '/docs/concepts/token-savings/',
    '/docs/tree-sitter/': '/docs/concepts/read-modes/',
    '/docs/verification/': '/docs/security/',
    '/docs/team-server/': '/docs/getting-started/',
    '/docs/team-setup/': '/docs/getting-started/',
    '/docs/cli/': '/docs/cli-reference/',
    '/docs/configuration/env-vars/': '/docs/configuration/',

    // Deleted guides
    '/docs/guides/docker/': '/docs/getting-started/',
    '/docs/guides/editor-integrations/': '/docs/getting-started/',
    '/docs/guides/first-session/': '/docs/getting-started/',
    '/docs/guides/observatory/': '/docs/getting-started/',
    '/docs/guides/workflow-blueprint/': '/docs/getting-started/',

    // Individual tool pages → tools overview
    '/docs/tools/ctx-read/': '/docs/tools/core/',
    '/docs/tools/ctx-search/': '/docs/tools/core/',
    '/docs/tools/ctx-tree/': '/docs/tools/core/',
    '/docs/tools/ctx-shell/': '/docs/tools/core/',
    '/docs/tools/ctx-edit/': '/docs/tools/core/',
    '/docs/tools/ctx-multi-read/': '/docs/tools/core/',
    '/docs/tools/ctx-overview/': '/docs/tools/core/',
    '/docs/tools/ctx-preload/': '/docs/tools/core/',
    '/docs/tools/ctx-prefetch/': '/docs/tools/core/',
    '/docs/tools/ctx-smart-read/': '/docs/tools/core/',
    '/docs/tools/ctx-expand/': '/docs/tools/core/',
    '/docs/tools/ctx-fill/': '/docs/tools/core/',
    '/docs/tools/ctx-delta/': '/docs/tools/core/',
    '/docs/tools/ctx-dedup/': '/docs/tools/core/',
    '/docs/tools/ctx-compress/': '/docs/tools/core/',
    '/docs/tools/ctx-compress-memory/': '/docs/tools/memory/',
    '/docs/tools/ctx-session/': '/docs/tools/session/',
    '/docs/tools/ctx-knowledge/': '/docs/tools/memory/',
    '/docs/tools/ctx-agent/': '/docs/tools/session/',
    '/docs/tools/ctx-handoff/': '/docs/tools/session/',
    '/docs/tools/ctx-share/': '/docs/tools/session/',
    '/docs/tools/ctx-intent/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-graph/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-graph-diagram/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-index/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-symbol/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-impact/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-callers/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-callees/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-callgraph/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-semantic-search/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-discover/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-discover-tools/': '/docs/tools/intelligence/',
    '/docs/tools/ctx-architecture/': '/docs/tools/analysis/',
    '/docs/tools/ctx-analyze/': '/docs/tools/analysis/',
    '/docs/tools/ctx-smells/': '/docs/tools/analysis/',
    '/docs/tools/ctx-review/': '/docs/tools/analysis/',
    '/docs/tools/ctx-outline/': '/docs/tools/analysis/',
    '/docs/tools/ctx-routes/': '/docs/tools/analysis/',
    '/docs/tools/ctx-benchmark/': '/docs/tools/analysis/',
    '/docs/tools/ctx-metrics/': '/docs/tools/analysis/',
    '/docs/tools/ctx-cost/': '/docs/tools/analysis/',
    '/docs/tools/ctx-heatmap/': '/docs/tools/analysis/',
    '/docs/tools/ctx-gain/': '/docs/tools/analysis/',
    '/docs/tools/ctx-workflow/': '/docs/tools/workflow/',
    '/docs/tools/ctx-task/': '/docs/tools/workflow/',
    '/docs/tools/ctx-verify/': '/docs/tools/workflow/',
    '/docs/tools/ctx-proof/': '/docs/tools/workflow/',
    '/docs/tools/ctx-execute/': '/docs/tools/workflow/',
    '/docs/tools/ctx-pack/': '/docs/tools/workflow/',
    '/docs/tools/ctx-wrapped/': '/docs/tools/workflow/',
    '/docs/tools/ctx-call/': '/docs/tools/workflow/',
    '/docs/tools/ctx-response/': '/docs/tools/workflow/',
    '/docs/tools/ctx-feedback/': '/docs/tools/workflow/',
    '/docs/tools/ctx-context/': '/docs/tools/core/',
    '/docs/tools/ctx-provider/': '/docs/tools/core/',
    '/docs/tools/ctx-artifacts/': '/docs/tools/workflow/',
    '/docs/tools/ctx-cache/': '/docs/tools/core/',

    // Locale redirects → homepage
    '/de/': '/',
    '/ar/': '/',
    '/zh/': '/',
    '/hi/': '/',
    '/es/': '/',
    '/fr/': '/',
    '/bn/': '/',
    '/pt/': '/',
    '/ru/': '/',
    '/ja/': '/',
  },
  integrations: [
    sitemap({
      filter: (page) => !page.includes('/index-backup/'),
    }),
  ],
  vite: {
    plugins: [tailwindcss()]
  }
});
